default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 60 } %>

development:
  <<: *default
  database: megapop_development

production:
  <<: *default
